### ISSUE TITLE
Building library fails in Windows

### ISSUE THREAD

**Issue by s-and-witch** [fizruk/telegram-bot-simple#105] opened 2022-03-18 17:50 UTC
![image](https://user-images.githubusercontent.com/74188979/159056695-550dd164-be98-446f-8dd6-7ef679de25de.png)

**Comment by Allody22** [comment] 2022-03-21 09:13
I also have this problem.  Ping me if you know how to solve this

**Comment by zlonast** [comment] 2022-03-22 07:48
I will take part in this (Windows installation sounds)

**Comment by zlonast** [comment] 2022-03-22 12:28
I have some solution without unix (but game-bot not building now) [my pull request](https://github.com/fizruk/telegram-bot-simple/pull/106)

**Comment by zlonast** [comment] 2022-03-22 12:30
![image](https://user-images.githubusercontent.com/20256537/159482209-9762fc65-4629-4951-b47b-eb11400a525d.png)
<img width="371" alt="Снимок экрана 2022-03-22 в 20 29 53" src="https://user-images.githubusercontent.com/20256537/159482354-49b9af85-f9d6-4ed5-a4a2-1df64dae4108.png">

**Comment by swamp-agr** [comment] 2022-03-22 12:56
Thank you for identifying the root cause of the issue.
I would argue with the fix. Instead of removing game from cabal/hpack package description, I would propose instead to make `unix` optional platform-dependant. The same will be applicable for all:
- `package.yaml`.
- `telegram-bot-simple.cabal`
- `GameBot` module.

**Comment by zlonast** [comment] 2022-03-22 14:09
> Thank you for identifying the root cause of the issue. I would argue with the fix. Instead of removing game from cabal/hpack package description, I would propose instead to make `unix` optional platform-dependant. The same will be applicable for all:
> 
> * `package.yaml`.
> * `telegram-bot-simple.cabal`
> * `GameBot` module.

i think unix is useless and we need to use signal [(my new pr)](https://github.com/fizruk/telegram-bot-simple/pull/107)

**Comment by swamp-agr** [comment] 2022-03-22 16:34
Closed via #107. 
Released on hackage: https://hackage.haskell.org/package/telegram-bot-simple-0.4.4

**Closed as completed by swamp-agr** 2022-03-22 16:34 UTC
